#ifndef DAMIAO_SWITCH_POWER_H
#define DAMIAO_SWITCH_POWER_H

#define Power_OUT1_ON 			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET)
#define Power_OUT1_OFF 			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET)

#define Power_OUT2_ON 			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_SET)
#define Power_OUT2_OFF 			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_RESET)

#endif //DAMIAO_SWITCH_POWER_H